FlashTest v1.0 started by Andi on Fri Oct  7 12:23:28 2016
Original command-line: ./flashTest.py UnitTest/
This invocation: 2016-10-07
--------------------------------------------------------------------------------
ERROR:   "/data/flash/" does not exist or is not a directory.
WARNING: FLASH source at "/data/flash/" was not updated
--------------------------------------------------------------------------------
12:23:28 Parsed "docker/UnitTest"
12:23:28 Creating directory "/Users/Andi/Development/CMDV/flashTest/output/docker/2016-10-07/UnitTest"
         ****** "test.info" ******
         setupName: unitTest/ACME
         setupOptions: --help
         numProcs: 1
         parfiles: <defaultParfile>
         *************************
         ** setup phase **
12:23:28 /data/flash/setup unitTest/ACME --help
